name: Validate PR Action

description: |
  A custom action to validate PR paths for master and tiddlywiki-com branches.

inputs:
  repo:
    description: 'The repository name in the format "owner/repo".'
    required: true
  pr_number:
    description: 'The pull request number.'
    required: true
  base_ref:
    description: 'The base branch of the pull request.'
    required: true
  github_token:
    description: 'GitHub token for API requests.'
    required: true

runs:
  using: 'node20'
  main: bin/ci-pr-validation/validate-branch.js
