name: PR Branch-Path Validation Example (Trusted workflow)

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use PR validation action
      uses: TiddlyWiki/cerebrus@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pr-number: ${{ github.event.pull_request.number }}
        base-ref: ${{ github.base_ref }}
        repo: ${{ github.repository }}